name: Validate config

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    validate-config:
        name: Validate
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

            - name: Setup node
              uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
              with:
                node-version: 20
                cache: 'npm'
                cache-dependency-path: 'Makefile'

            - name: Validate the config
              run: make validate-config
