name: Validate config

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    validate-config:
        name: Validate
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

            - name: Setup node
              uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
              with:
                node-version: 20
                cache: 'npm'
                cache-dependency-path: 'Makefile'

            - name: Validate the config
              run: make validate-config
